version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: linkarr-postgres
    environment:
      POSTGRES_USER: linkarr
      POSTGRES_PASSWORD: linkarr_password
      POSTGRES_DB: linkarr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkarr"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: linkarr-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkarr-backend
    environment:
      - DATABASE_URL=postgresql://linkarr:linkarr_password@postgres:5432/linkarr
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - RD_API_BASE_URL=https://api.real-debrid.com/rest/1.0
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkarr-celery-worker
    environment:
      - DATABASE_URL=postgresql://linkarr:linkarr_password@postgres:5432/linkarr
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - RD_API_BASE_URL=https://api.real-debrid.com/rest/1.0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A app.tasks.celery_app worker --loglevel=info

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkarr-celery-beat
    environment:
      - DATABASE_URL=postgresql://linkarr:linkarr_password@postgres:5432/linkarr
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - RD_API_BASE_URL=https://api.real-debrid.com/rest/1.0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A app.tasks.celery_app beat --loglevel=info

volumes:
  postgres-data:
